### ISSUE TITLE
Docker image build fails

### ISSUE THREAD

**Issue by sujaypillai** [Alfresco/SearchServices#1]
Trying to build the docker image according to the steps in [documentation](https://github.com/Alfresco/SearchServices/blob/master/README.MD) fails.

<img width="902" alt="screenshot 2017-01-30 14 18 40" src="https://cloud.githubusercontent.com/assets/3936714/22414837/c040e9f2-e6fd-11e6-96c2-abb36bfe31a2.png">

**Comment by covolution** [comment]
I am thinking of removing the banana integration, its not really fit for purpose at the moment.  You are calling the banana build.  If you want a docker image without banana you can try the buildAndTest.sh at the root of the packaging directory.

**Comment by sujaypillai** [comment]
Ok the docker image without banana integration works. In that case you may update the document for the right path "cd packaging/src/docker" to "cd packaging".
Just curious what is the use of package - "vim curl" in the Dockerfile?

**Comment by covolution** [comment]
Documentation updated
