### ISSUE TITLE
JavaDoc for the CommitTracker class

### ISSUE THREAD

**Issue by Artemas-Muzanenhamo** [Alfresco/SearchServices#11]
https://github.com/Alfresco/SearchServices/blob/eda67050e2b2e54f16a9300556f0dd581ad9856f/alfresco-search/src/main/java/org/alfresco/solr/tracker/CommitTracker.java#L31

Hi guys, firstly I want to say what a great job you guys are doing here ! :muscle: . I was wondering if we can get some JavaDoc briefly (1-2 sentences) on what the Commit tracker's purpose is if that's possible? Thanks. 😄

**Comment by harrypeek** [comment]
Hi Artemas, thanks for the feedback! I think a good place to start might be Andy's blog here: https://community.alfresco.com/people/andy1/blog/2018/01/09/search-the-overview

Under the 'Building Indexes' section it talks about the Commit Tracker, see if that helps and let us know if you have other questions.

**Comment by Artemas-Muzanenhamo** [comment]
@harrypeek Great Thanks !! I think the blog has great information. I'll close this issue anyways 👍
