### ISSUE TITLE
target without solr / alfresco artefacts only

### ISSUE THREAD

**Issue by hi-ko** [Alfresco/SearchServices#197]
we still prefer installing Alfresxo Search Services the traditional way without docker and solr from the solr project.
Could you please provide in future releases:
* release notes (containing the solr version as a dependency)
* a build with the alfresco artefacts only / without solr itself

We want to install solr the solr way as recommended by the solr team. Your

**Comment by tpage-alfresco** [comment]
It's still possible to install Search Services without Docker. Our zip contains the supported version of Solr (6.6.5 for recent releases) and you can install this using the instructions here:
https://docs.alfresco.com/search-enterprise/tasks/solr-install.html

We have more information about how this zip is built here:
https://github.com/Alfresco/SearchServices/tree/master/search-services

You can also find the solr version declared in the source code here:
https://github.com/Alfresco/SearchServices/blob/master/pom.xml#L30

The Alfresco jars can be found in Nexus or can be built from source, but the supported installation methods are detailed in our docs.

**Comment by hi-ko** [comment]
Hi Tom,
thanks for your feedback. I'm pretty aware about the docs you referenced.
The reason for focusing on the alfresco artefacts (and patched resources) only is that we and our customers want to be as close as possible to the solr common and known deployment and Filesystem Hierarchy Standard (e.g. /var/lib /etc/default ...) as possible and to store the index and index backups in the expected directories (/opt/alfresco/alf_data/).
So we don't just extract your zip

A release containing all except solr release would be perfect.

**Comment by aborroy** [comment]
Hi, @hi-ko 

An Alfresco Search Services release includes following changes in default SOLR Distribution.

We are starting from https://archive.apache.org/dist/lucene/solr/6.6.5/solr-6.6.5.zip

* Changes in scripts to start the service under folder bin (`solr.cmd`). We are releasing also enhanced scripts named `solr.in.cmd` and `solr.in.sh`
* Changes in default `/server/etc/jetty-ssl.xml` to include default Alfresco settings
* Libraries required for Alfresco integration with SOLR in `WEB-INF/lib` folder
  * Includes patched SOLR 6.6.5 libraries
  * Includes bumped version of some libraries
* Alfresco SOLR cores configuration, alfresco models and core templates in `solrhome` folder

**Alfresco Libraries**
 HikariCP-java7-2.4.13.jar
 ST4-4.0.8.jar
 acegi-security-0.8.2_patched.jar
 alfresco-core-7.21.jar
 alfresco-data-model-8.48.jar
 alfresco-search-1.5.0-SNAPSHOT.jar
 alfresco-solrclient-lib-1.5.0-SNAPSHOT.jar
 alfresco-xmlfactory-1.3.jar
 antlr-3.5.2.jar
 antlr-runtime-3.5.2.jar
 apache-mime4j-core-0.7.2.jar
 apache-mime4j-dom-0.7.2.jar
 aspectjrt-1.8.0.jar
 attributes-binder-1.3.1.jar
 bcmail-jdk15-1.45.jar
 bcprov-jdk15-1.45.jar
 boilerpipe-1.1.0.jar
 carrot2-guava-18.0.jar
 carrot2-mini-3.15.0.jar
 chemistry-opencmis-commons-api-1.1.0.jar
 chemistry-opencmis-commons-impl-1.1.0.jar
 chemistry-opencmis-server-bindings-1.0.0.jar
 chemistry-opencmis-server-support-1.0.0.jar
 commons-collections4-4.1.jar
 commons-compress-1.14.jar
 commons-httpclient-3.1-HTTPCLIENT-1265.jar
 commons-lang3-3.9.jar
 commons-logging-1.2.jar
 curvesapi-1.04.jar
 cxf-core-3.0.12.jar
 cxf-rt-bindings-soap-3.0.12.jar
 cxf-rt-bindings-xml-3.0.12.jar
 cxf-rt-databinding-jaxb-3.0.12.jar
 cxf-rt-frontend-jaxws-3.0.12.jar
 cxf-rt-frontend-simple-3.0.12.jar
 cxf-rt-transports-http-3.0.12.jar
 cxf-rt-ws-addr-3.0.12.jar
 cxf-rt-ws-policy-3.0.12.jar
 cxf-rt-wsdl-3.0.12.jar
 fontbox-2.0.6.jar
 guessencoding-1.4.jar
 icu4j-56.1.jar
 isoparser-1.1.18.jar
 jackcess-2.1.8.jar
 java-libpst-0.8.1.jar
 javax.activation-api-1.2.0.jar
 javax.servlet-api-3.1.0.jar
 jaxb-api-2.3.1.jar
 jaxb-core-2.3.0.1.jar
 jaxb-impl-2.3.2.jar
 jaxb-xjc-2.3.2.jar
 jaxen-1.2.0.jar
 jcl-over-slf4j-1.7.7.jar
 jdom-1.0.jar
 jempbox-1.8.13.jar
 jibx-run-1.3.1.jar
 jmatio-1.2.jar
 json-20160212.jar
 jsonic-1.2.7.jar
 jta-1.1.jar
 jug-2.0.0-asl.jar
 juniversalchardet-1.0.3.jar
 langdetect-1.1-20120112.jar
 metadata-extractor-2.9.1.jar
 morfologik-fsa-2.1.1.jar
 morfologik-polish-2.1.1.jar
 morfologik-stemming-2.1.1.jar
 mybatis-3.3.0.jar
 mybatis-spring-1.2.5.jar
 neethi-3.0.3.jar
 pdfbox-2.0.6.jar
 pdfbox-tools-2.0.6.jar
 poi-3.17-beta1.jar
 poi-ooxml-3.17-beta1.jar
 poi-ooxml-schemas-3.17-beta1.jar
 poi-scratchpad-3.17-beta1.jar
 quartz-2.3.1.jar
 rome-1.5.1.jar
 simple-xml-2.7.1.jar
 spring-aop-5.1.8.RELEASE.jar
 spring-beans-5.1.8.RELEASE.jar
 spring-context-5.1.8.RELEASE.jar
 spring-context-support-5.1.8.RELEASE.jar
 spring-core-5.1.8.RELEASE.jar
 spring-expression-5.1.8.RELEASE.jar
 spring-jcl-5.1.8.RELEASE.jar
 spring-jdbc-5.1.8.RELEASE.jar
 spring-orm-5.1.8.RELEASE.jar
 spring-surf-core-7.8.jar
 spring-surf-core-configservice-7.8.jar
 spring-tx-5.1.8.RELEASE.jar
 spring-web-5.1.8.RELEASE.jar
 tagsoup-1.2.1.jar
 tika-core-1.16.jar
 tika-java7-1.16.jar
 tika-parsers-1.16.jar
 tika-xmp-1.16.jar
 vorbis-java-core-0.8.jar
 vorbis-java-tika-0.8.jar
 wsdl4j-1.6.3.jar
 xercesImpl-2.11.0-alfresco-patched-20180402.jar
 xml-apis-1.4.01.jar
 xml-resolver-1.2.jar
 xmlbeans-2.6.0.jar
 xmlschema-core-2.2.1.jar
 xmpcore-5.1.2.jar
 xpp3-1.1.3_8.jar
 xz-1.6.jar

**Bumped Libraries**
 dom4j-2.1.1.jar
 jackson-annotations-2.10.0.pr2.jar
 jackson-core-2.10.0.pr2.jar
 jackson-databind-2.10.0.pr2.jar
 

**Patched Libraries**
lucene-analyzers-common-6.6.5-patched.jar
 lucene-analyzers-icu-6.6.5-patched.jar
 lucene-analyzers-kuromoji-6.6.5-patched.jar
 lucene-analyzers-morfologik-6.6.5-patched.jar
 lucene-analyzers-phonetic-6.6.5-patched.jar
 lucene-analyzers-smartcn-6.6.5-patched.jar
 lucene-analyzers-stempel-6.6.5-patched.jar
 lucene-backward-codecs-6.6.5-patched.jar
 lucene-classification-6.6.5-patched.jar
 lucene-codecs-6.6.5-patched.jar
 lucene-core-6.6.5-patched.jar
 lucene-expressions-6.6.5-patched.jar
 lucene-grouping-6.6.5-patched.jar
 lucene-highlighter-6.6.5-patched.jar
 lucene-join-6.6.5-patched.jar
 lucene-memory-6.6.5-patched.jar
 lucene-misc-6.6.5-patched.jar
 lucene-queries-6.6.5-patched.jar
 lucene-queryparser-6.6.5-patched.jar
 lucene-sandbox-6.6.5-patched.jar
 lucene-spatial-extras-6.6.5-patched.jar
 lucene-suggest-6.6.5-patched.jar
 solr-analysis-extras-6.6.5-patched.jar
 solr-clustering-6.6.5-patched.jar
 solr-core-6.6.5-patched.jar
 solr-langid-6.6.5-patched.jar
 solr-solrj-6.6.5-patched.jar
 
These changes has been done (mainly) to solve SOLR Vulnerabilities.

*So if you want to start with a SOLR standard distribution, you need to apply some changes on default configuration*

**Comment by michaelsuzukisagi** [comment]
@hi-ko,
Please note that Alfresco Search may be based on Solr but its not Solr. The setup differs from Solr and will contain elements that will not be found in Solr. Just as an example we use something known as a ContentStore which is an Alfresco feature, as a result the configuration will differ.
If you are concerned with backup and index, this is configurable to the location you would like it to be, so if you would want to store the data and backup to how the installer was set with /opt/alfresco/data that is still possible. Hope this helps, if I have misunderstood your query please let us know. 
As for the release notes we are happy to include the patch solr version we are using.

**Comment by hi-ko** [comment]
@tpage-alfresco, @aborroy, @michaelsuzukisagi thanks a lot for your valuable input!
So it was a misunderstanding: ass is _not_ a solr6 from scratch with alfresco extensions using the solr extensions points.
Ticket can be closed. 

We will continue like in the past to extract the zip to different locations and reconfigure storage locations and variables.

The only thing we didn't get working as expected are the data dirs by setting env variables (at least one of both will be ignored):

    SOLR_CONTENT_DIR=/opt/alfresco/alf_data/solr/
    SOLR_SOLR_MODEL_DIR=/opt/alfresco/alf_data/solr/alfrescoModel

so we endet up in setting them in jvm -D params:

    SOLR_OPTS="$SOLR_OPTS -Dsolr.solr.content.dir=/opt/alfresco/alf_data/solr/contentstore"
    SOLR_OPTS="$SOLR_OPTS -Dsolr.solr.model.dir=/opt/alfresco/alf_data/solr/alfrescoModels"
