### ISSUE TITLE
Enable date-related functions

### ISSUE THREAD

**Issue by HansDeBal** [Alfresco/SearchServices#210]
See https://hub.alfresco.com/t5/alfresco-content-services-forum/limitations-search-and-insights-engine/td-p/293384

It would be great if it would be possible to report on dates and more specific on throughput time (so date-differences). How long was a case open? What was the throughput time of a certain workflow per user/department? ...

**Comment by aborroy** [comment]
Thanks for your contribution, @HansDeBal 

A new ticket has been created to track this request:
https://issues.alfresco.com/jira/browse/SEARCH-1905

Closing this from this project.
