### ISSUE TITLE
GC / OOM problems with Alfresco Search Services and OpenJDK11

### ISSUE THREAD

**Issue by hi-ko** [Alfresco/SearchServices#233]
I updated Alfresco Search Services from 1.3 to 1.4 which forced me to also update OpenJDK from 8 to 11. Running Alfresco Search Services 1.3 with jdk8 worked without any OutOfMemoryExceptions during (re)indexing but with jdk11 we see repeatable growing the heap until the solr oom killer kills the solr process. During indexing the jvm performs continuously GC with jdk8 but I guess jdk11 changed GC in a way that the objects will stay longer in memory. Continuous GC indicates inefficient object creatrion but this is nothing I can influence. I tried with UseConcMarkSweepGC and G1 garbage collector but with the same behavior. What is the recommended way to configure GC with OpenJDK 11 to behave similar as in OpenJDK8 with Alfresco Search Services / solr6?

My parameters in solr.in.sh
````
SOLR_JAVA_MEM="-Xms16g -Xmx30g"
SOLR_OPTS="$SOLR_OPTS -Dsolr.jetty.request.header.size=1000000 -Dsolr.jetty.threads.stop.timeout=300000 -Ddisable.configEdit=true -Dsolr.allow.unsafe.resourceloading=true"
SOLR_OPTS="$SOLR_OPTS -XX:+UseConcMarkSweepGC -XX:-DisableExplicitGC -XX:-UseGCOverheadLimit"
SOLR_OPTS="$SOLR_OPTS -server -Djava.net.preferIPv4Stack=true -Duser.language=en -Duser.country=US -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.net.preferIPv6Addresses=false"
SOLR_OPTS="$SOLR_OPTS -Dsun.security.ssl.allowUnsafeRenegotiation=true -Dsolr.allow.unsafe.resourceloading=true"
````
please also check Question on Stack Overview:
[GC / OOM problems with Alfresco Search Services and OpenJDK11](https://stackoverflow.com/questions/59245375/gc-oom-problems-with-alfresco-search-services-and-openjdk11)

**Comment by aborroy** [comment]
Did you try this approach?

https://clouderatemp.wpengine.com/blog/2017/06/solr-memory-tuning-for-production-part-2/

**Comment by hi-ko** [comment]
@aborroy thanks for your hint. It's worth a try to use G1 even we are running with < 28 GB jvm. I think the recommendation for CMS does only apply for jdk8 but ASS-1.4 runs only with jdk11.

I guess the GC problems we have only during reindexing has to do with the ASS behavior AFaust mentioned in irc a week ago that every new entry will be updated once inserted. I will spend some more effords in GC tuning/monitoring next month. For now #232 has a much higher prio which unfortunately has been closed (for my understanding unresolved). #232 is a show stopper for all upcoming Alfresco 6.x migrations.

**Comment by hi-ko** [comment]
We tested with 28 G heap, 8 cores and G1 but still get OOM during reindexing. G1 seems not to handle the strange object deletion directly after creation very well. Please try yourself reindexing > 50 Mio nodes with jdk11. If you find out a tuning hint getting memory not to explode I would be thankful.

**Comment by aborroy** [comment]
Take a look at https://issues.alfresco.com/jira/browse/SEARCH-2066

Hope this helps.

**Comment by tomekkup** [comment]
Got same issue. Tried out with few gc parameters without any success. My Solr dies in 5 minutes after startup (16GB heap, about 20GB of index on disk).

**Comment by aborroy** [comment]
If it's SOLR 6, then try with recommended parameters from Apache:
https://github.com/apache/lucene-solr/blob/releases/lucene-solr/6.6.5/solr/bin/solr#L1813

**Comment by tomekkup** [comment]
I'm using standalone installation and mentioned params are 'default' in `solr.sh`. Already tried out. Problem still exists even if i decrease batch count etc

**Comment by aborroy** [comment]
Without additional data it's almost impossible to guess what's happening there...

**Comment by hi-ko** [comment]
Same here. we didn't migrate to Alfresco 6 for this reason.
To reproduce the issue you just need several million nodes to reindex. It looks like there is a fundamental change from alfresco solr4 to sol6 in updating the solr doc again after insert which results in tons of index segments which will never consolidated.

**Comment by aborroy** [comment]
We have internal tests with 1 billion documents, so my feeling it's like this is not so easy to reproduce. I'd love to help, but I need additional data in order to start a spike.

**Comment by hi-ko** [comment]
@aborroy did your tests include fulltext and metadata? We used 20% emails and 60% office docs/pdfs

we had some success by excluding xml, json and other non txt formats from transforming but this does not change the massive use case of changes after solr doc creation during reindex resulting in massive segment fragmentation.

**Comment by hi-ko** [comment]
My guess is that we would have no problem if we only write a solr doc once per node.

**Comment by tomekkup** [comment]
Finally I found solution. I've downloaded vm image from Bitnami ale copied their config. So... I use Oracle JDK, default cores config (solrcore.properties) and following VM and GC params:

```
SOLR_JAVA_MEM="-Xms12g -Xmx12g"
GC_TUNE="-XX:+UseG1GC -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=250 -XX:+UseLargePages -XX:+AlwaysPreTouch"
```

@hi-ko I'm curious if this would help

**Comment by aborroy** [comment]
Reproduced partially this problem when using massively secondary associations for folders.

**Comment by hi-ko** [comment]
OK - I think we nailed the memory and reindexing problem down to secondary assocs on folders.
As a work around I wrote a scriping solution to find all secondaries on folders and to replace them with alfresco link nodes. Not ideal but somehow working since the solr tracker now avoids endless loops and OOM.
@tomekkup I guess your solution is to use jdk instead of jdk11. Could you please confirm?

For now we can assume a bug in the ASS tracker implementation not working (efficient) with secondary child assocs on folders which may reactivate an old discussion about how to avoid to replicate alfresco to solr on any path change.

**Comment by aborroy** [comment]
This has been solved with the release of Search Services 1.4.3.
More information available in https://hub.alfresco.com/t5/alfresco-content-services-blog/search-services-1-4-3-release/ba-p/301127

**Comment by zhihailiu** [comment]
I ran into the same OutOfMemory error with Alfresco search services 2.0.0. Sorry to comment on the cold case but this is the closest I can find. 

It is not clear which JDK version Alfresco search services 2.0.0 (Solr 6.6.5) should use. I currently run it with JDK 11, the same as Alfresco 6 requires. But Solr documentation (https://cgi.percipio.com/channels/933d1703-473d-43bd-a57f-ddbc6ce35965) states that "Lucene/Solr 7.0 was the first version that successfully passed our tests using Java 9 and higher. You should avoid Java 9 or later for Lucene/Solr 6.x or earlier."

I am curious about how & why secondary associations impact Solr indexing. My content model has extensive use of secondary associations. It would be a show stopper if I have to replace that with link object to get Solr indexing work.

Thanks!

**Comment by hi-ko** [comment]
In fact, the already quite old version of solr officially only supports jdk8, but the classes for ASS2.x are compiled with jdk11, so only jdk11 will work. But be careful: I just run into the trap that solr6 will not start with latest jdk11.0.9 release. Latest 11.0.4 seems to work. I didn't test with 2.0.0 but 1.4.3 worked for me on a large repo having lots of secondary child assocs on folders. The issue on older versions was a endless loop while following parents to collect the paths to be stored in the index for a given node.

**Comment by hi-ko** [comment]
@zhihailiu did you check [2.0.1](https://hub.alfresco.com/t5/alfresco-content-services-blog/search-services-2-0-1-release/ba-p/303712)? This version fixes some issues: [SEARCH-2529: High memory consumption during reindex](https://alfresco.atlassian.net/browse/SEARCH-2529) but the issue is not public. See [Search Services 2.0.1 Release](https://hub.alfresco.com/t5/alfresco-content-services-blog/search-services-2-0-1-release/ba-p/303712)

**Comment by zhihailiu** [comment]
@hi-ko thank you! It seems that search services 2.0.0 out-of-the-box JVM settings are still tuned for JDK 8 though. The command line shows CMS GC. G1 should be the default GC starting JDK 9. Are you running JDK 11 with CMS or have you switched to G1?

I will definitely check out 2.0.1.
