### ISSUE TITLE
Groups Sync API: Requesting only updated groups

### ISSUE THREAD

**Issue by dek-odoo** [Alfresco/SearchServices#236]
For syncing groups to other platforms, we need new or deleted groups.
Also the updated groups, group is considered updated if there are any changes in its members.

Please have a look on this question:
https://stackoverflow.com/questions/59261575/alfresco-sync-groups-apis-and-cmis

Thank you

**Comment by mikeh** [comment]
This doesn't appear to be an issue for Search Services. Please consider asking the question in our Community forums at https://hub.alfresco.com/
