### ISSUE TITLE
alfresco-solrclient-lib does not compile

### ISSUE THREAD

**Issue by michaelsuzukisagi** [Alfresco/SearchServices#262]
When running mvn install with JDK 1.8, all search services  projects compile with the exception of alfresco-solrclient-lib. The alfresco-solrclient-lib only seems to compile with JDK 11 when it should work with JDK 8 as well.

**Comment by aborroy** [comment]
Why it should work with JDK 8?

**Comment by hi-ko** [comment]
solr6 has less memory problems (most GC related) in jdk8 than running with jdk11
so I would vote +1 for getting jdk8 support back for ASS as long solr does not switch to jdk11

Going from jdk8 to jdk11 is a major switch - not only for development but also for maintenance

**Comment by tpage-alfresco** [comment]
Closing this. The latest code is only compatible with Java 11 and we don't have plans to add support for Java 8.
