### ISSUE TITLE
Issue with maven build on Mac OS Catalina

### ISSUE THREAD

**Issue by AnanthCoupa** [Alfresco/SearchServices#317]
When we build the Alfresco Search Services on Mac OS Catalina the final solr6 zip file in target is always corrupted.  
Had to comment the following lines in the POM file 

`<filtering>true</filtering>` 

This filtering seems to corrupt the jar file and also the final zip file which is created. So need to check if this issue is specific to Mac

**Comment by aborroy** [comment]
Many of the developers in the team are using Mac, and the zip is always produced fine.

What ZIP are you referring to?

Any other additional data that can help to identify the problem?

**Comment by AnanthCoupa** [comment]
When I build alfresco search services the target folder has the file 

/alfresco-search-services/target/solr.solr-6.6.5-patched.2.zip 

which is in corrupted state. You get error when unpacking this zip file

**Comment by aborroy** [comment]
Why are you using that file for?

You have detailed instructions on how to run Alfresco SOLR from source code in:
https://github.com/Alfresco/SearchServices/tree/master/search-services#start-alfresco-search-services-from-source

**Comment by AnanthCoupa** [comment]
I tried this instructions mentioned in read me and build was failing with the issue i mentioned above 

Getting the code using a Git client.

$ git clone https://github.com/Alfresco/SearchServices.git
Build the project using Maven.

$ cd SearchServices/search-services
$ mvn clean install
All the resources required to run Alfresco Search Services will be available under search-services/packaging/target folder, including the distribution ZIP for local installations. 


The mvn clean install files at the last step where the zip file is being unpacked
