### ISSUE TITLE
'insight-engine' child module is no longer exist.

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/SearchServices#364]
Since the `insight-engine` module does not exist in this repository, it is better to delete the setting from `pom.xml`.

https://github.com/Alfresco/SearchServices/blob/6c01e74de5d02e5b1e8150f4b6e7ec1984d7ce8b/pom.xml#L43

**Comment by aborroy** [comment]
This is a partially mirrored repository. 

`insight-engine` module exists in the source project. 

Insight Engine is the Enterprise part of the Search Services product, that includes features like SOLR JDBC connection.
