### ISSUE TITLE
Please fix/remove broken hyperlink url 'insight-engine' 

### ISSUE THREAD

**Issue by lifeofspice** [Alfresco/SearchServices#374]
in the master project there is a broken hyperlink url 'insight-engine'  , the hyperlink url is : https://github.com/Alfresco/SearchServices/blob/master/insight-engine 

this return 404 Not found when click. Please fix/remove broken hyperlink url 'insight-engine' 

====found in https://github.com/Alfresco/SearchServices/blob/master/  in below paragraph ===

Insight Engine
Following resources will not be available for Community users

More details are available at insight-engine folder.

===

**Comment by aborroy** [comment]
"Following resources will not be available for Community users"

That is an internal link, as this project is mirrored from internal repository **InsightEngine**. If you want to get access to that Enterprise repository, please contact support.
