### ISSUE TITLE
Both solr6 and solr6secondary share the same port.

### ISSUE THREAD

**Issue by am-tribia** [Alfresco/SearchServices#379]
Solr6Secondary fails to start and throws the following error

`ERROR: for sharding_solr6secondary_1  Cannot start service solr6secondary: driver failed programming external connectivity on endpoint sharding_solr6secondary_1`

Refer to the below code

https://github.com/Alfresco/SearchServices/blob/cb2a194fd7a36c7c7bc67c8190d286e83b1bc69f/e2e-test/generator-alfresco-docker-compose/generators/app/templates/7.0/docker-compose-ee.yml#L178

Both solr6 and solr6secondary share the same external port 8083. These external ports should be different for solr6 and solr6Secondary

**Comment by aborroy** [comment]
This will be fixed in the next release. Thanks.
