### ISSUE TITLE
Incorrect configuration

### ISSUE THREAD

**Issue by am-tribia** [Alfresco/SearchServices#380]
According to the below code the keystore is loaded from /usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore. I assume this Keystore is bundled along with the alfresco image

https://github.com/Alfresco/SearchServices/blob/cb2a194fd7a36c7c7bc67c8190d286e83b1bc69f/e2e-test/generator-alfresco-docker-compose/generators/app/templates/7.0/docker-compose-ee.yml#L23

But actually, we are mounting the generated keystore files as below.
https://github.com/Alfresco/SearchServices/blob/cb2a194fd7a36c7c7bc67c8190d286e83b1bc69f/e2e-test/generator-alfresco-docker-compose/generators/app/templates/7.0/docker-compose-ee.yml#L69

Looks like there is a misconfiguration here

**Comment by aborroy** [comment]
We are using default `keystore` file provided by repository, as this file is used for encryption (not related with mTLS) and this feature is not used.
