### ISSUE TITLE
Cannot override ssl.keystore.type in solrcore.properties

### ISSUE THREAD

**Issue by mcgitty** [Alfresco/SearchServices#381]
The design of CoreDescriptorDecorator and ConfigUtil allow a some solrcore.properties be overriden by external source: JNDI, Java System properties and environment variables. However, when "alfresco.secureComms=https", these 2 solrcore.properties cannot be overriden:

- alfresco.encryption.ssl.keystore.type
- alfresco.encryption.ssl.truststore.type

The bug is in the CoreDescriptorDecorator constructor's foreach loop at line 94 when ConfigUtil.locateProperty() return null, it will lead to a NullPointerException in put() and terminates the loop.

If solrcore.properties created from "solrhome/templates/..." have these two settings commented out or omitted:

- #alfresco.encryption.ssl.keystore.provider=
- #alfresco.encryption.ssl.truststore.provider=

the foreach loop will terminate due to the NPE when it reaches property "alfresco.encryption.ssl.keystore.provider", skipping both ...ssl.keystore.type and ...ssl.truststore.type set externally.

**Comment by aborroy** [comment]
May you detail the steps in order to reproduce this problem locally?

**Comment by mcgitty** [comment]
This bug is best explained by this pull request: https://github.com/Alfresco/SearchServices/pull/382

However, here are steps to reproduce it:

1. Run alfresco-ssl-generator to generate keystores in JKS format:
`./run.sh -keysize 2048 -alfrescoversion enterprise -alfrescoformat classic -keystoretype JKS -truststoretype JKS`

2. Follow this blog to configure everything (except the above command) but replace all mentions of JCEKS with JKS: ["A simplified guide to enable ACS Mutual TLS with Search Services"](https://hub.alfresco.com/t5/alfresco-content-services-blog/a-simplified-guide-to-enable-acs-mutual-tls-with-search-services/ba-p/308008)

3. Solr6 (jetty) will failed to start, complaining invalid keystore.

**Comment by aborroy** [comment]
I was able to get that working fine, without getting the NPE exception.

I've fixed the `solrcore.properties` from each core, from the blog post I guess these properties are missed:

```
alfresco.encryption.ssl.truststore.passwordFileLocation=ssl-truststore-passwords.properties
alfresco.encryption.ssl.keystore.passwordFileLocation=ssl-keystore-passwords.properties
```

[solrcore.txt](https://github.com/Alfresco/SearchServices/files/6853690/solrcore.txt)

Can you verify you configuration is including these values?

**Comment by mcgitty** [comment]
The blog does have those 2 lines, last I checked. What is the output of this command for you?
`grep ^SOLR_SSL search-services/solr.in.sh`

**Comment by aborroy** [comment]
Not sure, I removed the configuration after the test.

Without a trustable method to reproduce the problem, it's hard to consider your contribution.

Can you provide additional details on this?

**Comment by mcgitty** [comment]
I compared my solrcore with yours and found the issue. If you comment out one or both of these lines in solrcore.properties, the NPE will be logged in solr.log:
`#alfresco.encryption.ssl.keystore.provider=`
`#alfresco.encryption.ssl.truststore.provider=`

The description of these two settings is:

> This property specifies the Java provider that implements the type  attribute (for example, JCEKS type). The provider can be left  unspecified and the first provider that implements the keystore type  specified is used.

The word "unspecified" can be interpreted as "not having the setting at all" instead of "must be set to empty string". This bug is still valid. Please try again to reproduce and verify. Thanks

**Comment by aborroy** [comment]
I was able to reproduce the issue with those instructions.

May you provide following changes?

* Java code reworked to comply with Java 11
* Simple Unit Test

Thanks

**Comment by mcgitty** [comment]
- Please see [PR 382](https://github.com/Alfresco/SearchServices/pull/382). It is ready and will compile and run in Java 11. 
- Let me work on the unit test case and will add it to [PR 382](https://github.com/Alfresco/SearchServices/pull/382).

**Comment by mcgitty** [comment]
@aborroy Unit test added to [PR 382](https://github.com/Alfresco/SearchServices/pull/382).

**Comment by aborroy** [comment]
Solved by https://github.com/Alfresco/SearchServices/commit/cb324f73972fc91eddd2067dcd9ab7ab3b2790cb
Thanks @mcgitty
