### ISSUE TITLE
Generator Alfresco Docker Compose

### ISSUE THREAD

**Issue by marcogianini** [Alfresco/SearchServices#385]
Hi,

i can't install generator-alfresco-docker-compose and run yo alfresco-docker-compose.

I have yo successfully installed, and nodejs as well.

I try to install without using the npm link and it does not find.

What is the best way forward?

Thanks

**Comment by aborroy** [comment]
You may try using "npm install" and "npm link" after that.

**Comment by marcogianini** [comment]
Angel, good morning.

I did exactly as the documentation you created says.

I install yo and then npm link and it says it doesn't find generator-alfresco-docker-compose

I don't know if I need to point the npn link somewhere.

Marco

**Comment by aborroy** [comment]
Try "npm update" and "npm link" from "generator-alfresco-docker-compose" folder.

**Comment by marcogianini** [comment]
Thanks, that´s correct.
