### ISSUE TITLE
Contentstore Volume missing

### ISSUE THREAD

**Issue by deas** [Alfresco/SearchServices#7]
I may be missing something, but for me, README.md instructions for building a Docker image don't work. Mostly due to the base image used.

However, I think you are missing a volume instruction
```
VOLUME /opt/alfresco-search-services/contentstore
```
along with associated `mkdir` in the Dockerfile.

**Comment by tpage-alfresco** [comment]
There's a good chance that something has been updated since this ticket was raised, but I just checked the instructions on master, and they seem to be working for me.

Closing this, but feel free to re-open if it is still broken for you.
