### ISSUE TITLE
Docker 'solrhome' volume limits image configuration

### ISSUE THREAD

**Issue by DanielFernandezPera** [Alfresco/SearchServices#78]
We are trying to create a new docker image extending from this and making some modifications to configuration:
`RUN set -x \
    && sed -i '/alfresco.cross.locale.datatype/s/^#//g' $DIST_DIR/solrhome/conf/shared.properties`
but 'solrhome' is a volume so our changes to the file are not recorded into de image.

We could provide a volume with 'solrhome' folder structure replicated but, Is there a better way?
Is it actually useful to include this directory as volume?

**Comment by michaelsuzukisagi** [comment]
Another option is to build your own image with the specific configuration. We can look into passing parameters to help configure the images in the future if this of helps.

**Comment by DanielFernandezPera** [comment]
Thank you for your fast response Michael!

You are correct. I have just tried to copy my specific configuration file when building the image and it seems to overwrite the volume contents. I would prefer using 'sed' to be more dynamic to changes in parent image but the 'COPY' approach gives me a better solution than providing full volume.

**Comment by angelborroy-ks** [comment]
I shared my approach at 
https://github.com/keensoft/docker-alfresco/wiki/Enabling-cross-locale-searching-for-SOLR-6

IMO is always better to use official images with customisations parameters, as in this way is easier to manage upgradings.

When customising Alfresco Repository image, you can always add / replace properties in `alfresco-global.properties` at will. So, again IMO, this `shared.properties` resource should behave in the same way.
